package com.controlmoblie.util

object AppResolver {

private val aliases = mapOf(
        "微信" to "com.tencent.mm",
        "qq" to "com.tencent.mobileqq",
        "qq音乐" to "com.tencent.qqmusic",
        "支付宝" to "com.eg.android.AlipayGphone",
        "淘宝" to "com.taobao.taobao",
        "京东" to "com.jingdong.app.mall",
        "抖音" to "com.ss.android.ugc.aweme",
        "快手" to "com.smile.gifmaker",
        "微博" to "com.sina.weibo",
        "哔哩哔哩" to "tv.danmaku.bili",
        "b站" to "tv.danmaku.bili",
        "bili" to "tv.danmaku.bili",
        "百度" to "com.baidu.searchbox",
        "百度地图" to "com.baidu.BaiduMap",
        "高德地图" to "com.autonavi.minimap",
        "地图" to "com.autonavi.minimap",
        "美团" to "com.sankuai.meituan",
        "外卖" to "com.sankuai.meituan",
        "饿了么" to "me.ele",
        "滴滴" to "com.sdu.didi.psnger",
        "打车" to "com.sdu.didi.psnger",
        "飞书" to "com.ss.android.lark",
        "钉钉" to "com.alibaba.android.rimet",
        "企业微信" to "com.tencent.wework",
        "企业号" to "com.tencent.wework",
        "小红书" to "com.xingin.xhs",
        "网易云音乐" to "com.netease.cloudmusic",
        "音乐" to "com.netease.cloudmusic",
        "酷狗" to "com.kugou.android",
        "设置" to "com.android.settings",
        "相机" to "com.android.camera",
        "电话" to "com.android.dialer",
        "拨号" to "com.android.dialer",
        "短信" to "com.android.mms",
        "联系人" to "com.android.contacts",
        "日历" to "com.android.calendar",
        "时钟" to "com.android.deskclock",
        "闹钟" to "com.android.deskclock",
        "计算器" to "com.miui.calculator",
        "天气" to "com.miui.weather2",
        "相册" to "com.miui.gallery",
        "文件" to "com.android.fileexplorer",
        "浏览器" to "com.android.browser",
        "小米浏览器" to "com.miui.browser",
        "应用商店" to "com.xiaomi.market",
        "米家" to "com.xiaomi.smarthome",
        "邮件" to "com.android.email",
        "邮箱" to "com.android.email",
        "今日头条" to "com.ss.android.article.news",
        "新闻" to "com.ss.android.article.news",
        "拼多多" to "com.xunmeng.pinduoduo",
        "闲鱼" to "com.taobao.idlefish",
        "12306" to "com.MobileTicket",
        "火车票" to "com.MobileTicket",
        "铁路" to "com.MobileTicket",
        "便签" to "com.miui.notes",
        "笔记" to "com.miui.notes",
        "指南针" to "com.miui.compass",
        "扫一扫" to "com.xiaomi.scanner",
        "扫" to "com.xiaomi.scanner"
    )

    fun resolve(name: String): String {
        return aliases[name] ?: name
    }
}